# Generated by Django 5.2.7 on 2025-10-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_planificada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='modelo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='odometro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='revisado_por',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_accion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='hh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='ot_management.ordentrabajo')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='ot_management.ordentrabajo')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('detalle', models.TextField()),
                ('tiempo_estimado', models.IntegerField(default=0)),
                ('tiempo_real', models.IntegerField(default=0)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='ot_management.ordentrabajo')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
    ]
