# Generated by Django 5.2.7 on 2025-10-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_management', '0002_ordentrabajo_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OT2025MecanicasRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(help_text='JSON dump of the row values')),
                ('fuente_archivo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OT 2025 Mecanicas - Raw row',
                'verbose_name_plural': 'OT 2025 Mecanicas - Raw rows',
                'db_table': 'ot_2025_mecanicas',
            },
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fila_origen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fuente_archivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='incompleta',
            field=models.BooleanField(default=False),
        ),
    ]
