# Generated by Django 5.2.7 on 2025-11-28 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_management', '0003_ot2025mecanicasraw_ordentrabajo_fila_origen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OT2025MecanicasRaw',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fila_origen',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fuente_archivo',
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
