# Generated by Django 5.2.7 on 2025-12-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot_management', '0004_delete_ot2025mecanicasraw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='mantencion_lograda',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'En Espera'), ('EN_PROCESO', 'En Ejecución'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20),
        ),
    ]
